// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhoneEdit.Data;

namespace PhoneEdit.Data.Migrations
{
    [DbContext(typeof(PhonebookContext))]
    [Migration("20190214095704_BookEntry")]
    partial class BookEntry
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PhoneEdit.Models.BookEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("n")
                        .HasColumnType("int(11)");

                    b.Property<string>("CityPhoneNumber")
                        .IsRequired()
                        .HasColumnName("telg")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnName("work")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("LocalPhoneNumber")
                        .IsRequired()
                        .HasColumnName("telm")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnName("mail")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("PersonnelNumber")
                        .IsRequired()
                        .HasColumnName("tabNumber")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnName("who")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnName("komnata")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Status")
                        .HasColumnName("status")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("tel1");
                });
#pragma warning restore 612, 618
        }
    }
}
